### PR TITLE
⚠ WIP:  TrackingIssue/#785

### LINKED ISSUE #785: Release 0.8
This ticket will be a reference to all issues for the next Release 0.8!
There are some small problems we can fix with this issues! Other will be related to this.

- [x] own badges with angular badges
- [ ] Use tree component for download
- [x] Course card should not have a fab button instead only a normal button
- [x] General tab in course edit translation is broken
- [x] Add spacing in download course between card top and text
- [x] Cancel in download course with no selection will through an error

### PR DESCRIPTION
**Pull request by HPunktOchs**
## Description:
Some small gathered Issues.
The Download code structure will be tidied up in another issue.

Closes #785 

## Improvements
- [x] own badges with angular badges
- [x] Course card should not have a fab button instead only a normal button
- [x] General tab in course edit translation is broken
- [x] Add spacing in download course between card top and text
- [x] Cancel in download course with no selection will through an error

### CODE REVIEW

File: api/src/models/Course.ts [hunk 1]
```diff
@@ -283,6 +283,7 @@ courseSchema.methods.forView = function (): ICourseView {
   return {
     _id: <string>extractMongoId(this._id),
     name, description,
+    name, description,
```
Comment (PatrickSkowronek) [inline api/src/models/Course.ts]: Why?

File: api/src/models/units/Unit.ts [hunk 2]
```diff
@@ -81,7 +81,8 @@ unitSchema.methods.exportJSON = function () {
 
   // custom properties
   delete obj._course;
-
+  console.dir('on export');
```
Comment (PatrickSkowronek) [inline api/src/models/units/Unit.ts]: Why?

File: api/src/models/units/Unit.ts [hunk 3]
```diff
@@ -81,7 +81,8 @@ unitSchema.methods.exportJSON = function () {
...
+  console.dir(obj);
```
Comment (PatrickSkowronek) [inline api/src/models/units/Unit.ts]: Why?

File: api/src/models/units/Unit.ts [hunk 4]
```diff
@@ -109,7 +110,8 @@ unitSchema.methods.toFile = function (): String {
 
 unitSchema.statics.importJSON = async function (unit: IUnit, courseId: string, lectureId: string) {
   unit._course = courseId;
-
+  console.dir('on import');
```
Comment (PatrickSkowronek) [inline api/src/models/units/Unit.ts]: Why?

File: api/src/models/units/Unit.ts [hunk 5]
```diff
@@ -109,7 +110,8 @@ unitSchema.methods.toFile = function (): String {
...
+  console.dir(unit);
```
Comment (PatrickSkowronek) [inline api/src/models/units/Unit.ts]: Why?
